# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='users',
            name='registered_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='webstore_url',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
