# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_users_webstore_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
